services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    restart: unless-stopped
