export * from './webhooks/interfaces/IgeneralResponseApi.js';
export * from './webhooks/interfaces/IwebhooksEvents.js';
export * from './webhooks/interfaces/IrequestWebhook.js';
export * from './webhooks/interfaces/IalertResponseWebhook.js';
export * from './webhooks/interfaces/IconfigApp.js';
export * from './webhooks/interfaces/ImessageBuilder.js';
export * from './webhooks/interfaces/IreportRoleUsers.js';
export * from './webhooks/interfaces/IbranchProtection.js';
export * from './webhooks/interfaces/IrepositoryData.js';